### ISSUE TITLE
Line	Suppression State Error CS1705	Assembly 'Lunar' with identity 'Lunar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, C70	Active

### ISSUE THREAD

**Issue by zortos293** [Dewera/Lunar#12]
how can fix it?

**Comment by Dewera** [comment]
Likely a .Net versioning issue. The current version of the library is written using .Net Core 3.1. Make sure you have the appropriate runtime/sdk installed.

**Comment by zortos293** [comment]
im trying to use lunar on net framework 4.7.1 tried downgrading same error

**Comment by Dewera** [comment]
As I mentioned previously, the library is written in **Core** not Framework. It will only work if you use the correct [runtime/sdk](https://dotnet.microsoft.com/download/dotnet-core/3.1).

It may be worth noting that the library will be upgraded to .Net 5 when it is released in November.
