### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: VCRUNTIME140.dll

### ISSUE THREAD

**Issue by shiversoftdev** [Dewera/Lunar#14]
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Lunar.Remote.ProcessContext.Refresh() in Lunar-master\Lunar\Remote\ProcessContext.cs:line 165
   at Lunar.LibraryMapper.LoadDependencies() in Lunar-master\Lunar\LibraryMapper.cs:line 575
   at Lunar.LibraryMapper.MapLibrary() in Lunar-master\Lunar\LibraryMapper.cs:line 127

![image](https://user-images.githubusercontent.com/30662495/99198471-5e73f980-275e-11eb-9a33-34a414103201.png)

Running as a .net 5 console app.

**Comment by Dewera** [comment]
Interesting issue, thanks for reporting this. Could you provide the DLL you are encountering this with? 

If you don't want to upload the DLL here you can add me on Discord (Quin#4576) and provide it there.

**Comment by shiversoftdev** [comment]
I'm sorry, I cant provide the DLL. It was not static linked though, which I've been told may contribute to the problem.

**Comment by Dewera** [comment]
Not being statically linked won't be the issue.

If you don't want to provide me with the DLL then I'm going to have some additional information as this is not very easy to debug without being able to replicate the issue.

My guess is that the DLL and process both have a dependency on a DLL, however, one of them is using a SxS version of said DLL, hence 2 DLLs are loaded in the process with the same name but they are different versions (and need to stay isolated for obvious reasons.)

To verify this could you please do the following (and report back the information I'm requesting)

- Verify whether your DLL uses a manifest to use a SxS dependency - If so what SxS DLL?
- Get a list of the DLL imports and a list of the loaded modules of the process before any mapping occurs
- If a DLL exists in both lists (via name,)  check the file path of the DLL in the process and check if it exists in some directory that resides in the WinSxS directory
- If this is the case, can you let me know if the process or the DLL being loaded is dependency on the SxS file path

**Comment by Dewera** [comment]
Fixed in 3d368db
