### ISSUE TITLE
Could not install package 'Lunar-RPatch 1.1.0'.

### ISSUE THREAD

**Issue by MaximusXYZ** [Dewera/Lunar#15]
I'm trying to install the package but I can't install it.
My project framework is .Net Framework 4.8 Dev,
If not fixed can I have the download instead?

Exception
`Severity	Code	Description	Project	Line	Suppression State	File
Error		Could not install package 'Lunar-RPatch 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		
`

**Comment by Dewera** [comment]
The latest version of the library targets .Net 5

Also where are you trying to install the library from? It isn't hosted on the official Nuget feed so you will have to get directly from this repository or from the GitHub package registry

**Comment by MaximusXYZ** [comment]
I downloaded 5.0 but it doesn't show on my list. I downloaded the dev one.

I also  don't know how to use the dotnet command line.

**Comment by Dewera** [comment]
I don't really understand what you mean sorry

**Comment by MaximusXYZ** [comment]
Is there anyway to download the latest version? I don't know how to use the dotnet command line.

**Comment by Dewera** [comment]
Download the repository and compile it yourself if you don't want to add the Nuget feed
