### ISSUE TITLE
Version Mismatch System.Runtime

### ISSUE THREAD

**Issue by LordLucifr** [Dewera/Lunar#17]
I have a Windows Forms Application in .Net Framework 4.7.2 and when i add the reference to lunar.dll it give me this error Severity	Code	Description	Project	File	Line	Suppression State
`Error	CS1705	Assembly 'Lunar' with identity 'Lunar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	PWNED Trainer`
Please help im unsure what i have done wrong here.

**Comment by Dewera** [comment]
The latest version of the library uses .Net 5 and won't work with anything less than that such as framework.
