### ISSUE TITLE
Execute injected dll's methods

### ISSUE THREAD

**Issue by ErcinDedeoglu** [Dewera/Lunar#18]
Could you give me an example for how to call remote method in injected DLL with Lunar?

**Comment by Dewera** [comment]
This library doesn't aim to provide mechanisms to execute remote methods after DLL loading, rather emulate the process of loading the DLL itself exclusively similar to that of the Windows loader - If this is something you are looking to do then you are going to have to do it yourself.

My suggestion would be one of the following

- Call your method inside DllMain resulting the in the method being executed during the mapping process
- Map the DLL with its headers intact and parse the export directory from said headers (found at `DllBaseAddress`) to find the address of the function you are trying to call, and then use one of the various execution methods like `CreateRemoteThread`, `QueueUserApc` etc
