### ISSUE TITLE
System.InvalidOperationException:“Sequence contains no elements”

### ISSUE THREAD

**Issue by scx1125** [Dewera/Lunar#2]
Hi, first of all thanks for your open source, but I encountered some errors when injecting the dll：System.InvalidOperationException:“Sequence contains no elements”

**Comment by Dewera** [comment]
I've had this issue reported to me already and it is has been addressed and fixed in my development version.

The 1.2 release will include a fix this, and it should be released relatively soon.

**Comment by Dryadepy** [comment]
hello @Dewera the issue still persist on the master

**Comment by Dewera** [comment]
@Dryadepy I will need you to provide me with the DLL so I can step through the mapping with a debugger to determine the issue.

Either attach on this thread or add me discord (Quin#4576) and send there.

**Comment by Dryadepy** [comment]
@Dewera I actually used dlls used on the test project (x64.dll).

**Comment by Dewera** [comment]
@Dryadepy I don't get this issue. Could you provide a stack trace please?

**Comment by Dewera** [comment]
Will be closing this issue as there doesn't seem to be any activity. I plan on releasing a large update in the near future, so if anyone reading this encounters this issue when 1.3 is released, please open a new issue and provide the relevant information.

**Comment by super-continent** [comment]
Any ETA on the update? I just found this library and I get the issue with a DLL I'm working on, but I would love to be able to use this library to make a simple injector to bundle with my library

**Comment by Dewera** [comment]
@super-continent Code is all done, just ironing out some stubborn bugs. Hopefully not too much longer. Can't guarantee this will fix your specific issue, so will need to do some testing and report back with a stack trace if it doesn't work.

**Comment by super-continent** [comment]
Cool, thank you for the quick reply! I'll hope for the best.

**Comment by Dewera** [comment]
@super-continent Could you test the latest version and let me know if this solves your problem? If not, please open a new issue and provide a stack trace.

**Comment by super-continent** [comment]
I'll test it out when I can and reply with results, thanks for the update.
