### ISSUE TITLE
Error on process with a DLL loaded multiple times

### ISSUE THREAD

**Issue by kast1450** [Dewera/Lunar#24]
"An item with the same key has already been added" at Lunar.Remote.ProcessContext.Refresh()

![](https://i.imgur.com/ln0MP6T.png)
![](https://i.imgur.com/ahQFnVD.png)

**Comment by Dewera** [comment]
Thanks for reporting. Regressed bug from latest update as I changed the way modules were iterated to simplify the codebase. Will fix in the near future
