### ISSUE TITLE
Importing problems

### ISSUE THREAD

**Issue by bacontsu** [Dewera/Lunar#30]
Predefined type 'System.Runtime.CompilerServices.IsExternallnit' is not defined or imported after i set the language version to 9.0. am i doing something wrong?

**Comment by bacontsu** [comment]
wait nevermind, i can just install it using NuGet im dumb

**Comment by bacontsu** [comment]
accidental close

**Comment by bacontsu** [comment]
this actually happened because i tried to import the package to .Net Framework, anyways to allow it?

**Comment by Dewera** [comment]
No, the library is written in .Net 5

**Comment by bacontsu** [comment]
> No, the library is written in .Net 5

ah i was thinking to use .Net Standard but i scrapped the whole thing and remade it on .Net Core 5.0, thanks for your help!
