### ISSUE TITLE
Map myself?

### ISSUE THREAD

**Issue by Bluespide** [Dewera/Lunar#34]
Hello,
is it not allowed to map a library to my own process? I'm trying this little sample code:
```
LibraryMapper mapper = new LibraryMapper(Process.GetCurrentProcess(), @"C:\Users\sam\Desktop\libwebp.dll");
mapper.MapLibrary();
```
But it just stucks at line 33 SymbolHandler -> GetSymbol -> Dbghelp.SymInitialize.

**Comment by Dewera** [comment]
Any more info? It just hangs on that call there's an exception?

**Comment by Bluespide** [comment]
![Stuck](https://user-images.githubusercontent.com/6599191/135602602-0eb44af3-1661-4e10-bb72-41e48476112a.png)
Windows 10 21H1
No Exception. Just stuck. If I pause the execution I see that he is waiting on that line.

**Comment by Dewera** [comment]
Thanks, I will check it out tomorrow and see if I can replicate the issue.

**Comment by Dewera** [comment]
Found the issue, turns out the Dbghelp api's don't play well with the PEB lock that is acquired by some of the mapping functions which was causing a deadlock. Seems to be fixed with the latest patch I just pushed through but if you can just confirm it works on your end that would be great.

**Comment by Bluespide** [comment]
Thank you, works!
