### ISSUE TITLE
when i inject to csgo the game freezes and crashes

### ISSUE THREAD

**Issue by widow-9098** [Dewera/Lunar#35]
i am using this code and i dont know why i crashes
```

           var process = Process.GetProcessById(id);
            var dllFilePath = @"dll.dll";
            var flags = MappingFlags.DiscardHeaders;
            var mapper = new LibraryMapper(process, dllFilePath, flags);
            mapper.MapLibrary();
```

**Comment by Dewera** [comment]
Gonna have to send through the DLL for me to take a look. Quin#4576 on discord

**Comment by Dewera** [comment]
I'm going to close this as there hasn't been a response and the latest commits have generally other issues with csgo. If you still have issues let me know.
