### ISSUE TITLE
Freezes on inject

### ISSUE THREAD

**Issue by CusYaBasic** [Dewera/Lunar#40]
Hey, I've added the lunar.dll as a reference to my loader.

I've also added this code:

```
Process process = Process.GetProcessesByName("")[0];
MappingFlags flags = MappingFlags.None;
LibraryMapper mapper = new LibraryMapper(process, GameDetails.DLLPath, flags);

mapper.MapLibrary();
```
But everytime the loader and the game freezes..

I've also tried with:
```
MappingFlags flags = MappingFlags.DiscardHeaders;
```

I still get the same issue. Am I missing something or doing anything wrong?

**Comment by Dewera** [comment]
Not really enough info here. What Windows version are you using? What process are you mapping into? Does the process have an anticheat?

**Comment by CusYaBasic** [comment]
> Not really enough info here. What Windows version are you using? What process are you mapping into? Does the process have an anticheat?

Sorry I should of been more clear..

I'm on a x64 system, but It's a 32-bit game/process I'm injecting into. It's only a singleplayer game so no anticheat.

My loaders made in C# (x86) and I can inject using "memory.dll" and it works so I know it's not my dll.
I can also use the GH injector which has a manual map setting which also works.

I wasn't sure if I was missing any steps or messing up somewhere.

**Comment by Dewera** [comment]
What is the Windows version? I.e. 22H2. Is there any chance you could send me the DLL as well? I can't replicate any issues with x86 mapping and all my test DLL's don't have issues. My discord is Dewera#5508 if so.
