### ISSUE TITLE
implement lunar into the simple injector

### ISSUE THREAD

**Issue by nikita-tarasov3** [Dewera/Lunar#5]
I read about c# and the library and didn't understand how to implement it. help me please!
tried a lot of time - fail. teach me please!
But im deleted Simple-Injection.dll from Simple Injector and removed link.
Then added Lunar.dll to project and added link of lunar.dll
**Program.cs:**
```
using System;
using System.Windows.Forms;
using Lunar;
using Simple_Injector.Etc;

namespace Simple_Injector
{
    public static class Program
    {
        private static readonly LibraryMapper libraryMapper = new LibraryMapper();

        private static readonly Status Status = new Status();

        [STAThread]
        public static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Interface());
        }

        public static Status Inject(Config config)
        {
            // Inject using specified method

            switch (config.InjectionMethod)
            {
                case "MapLibrary":

                    if (LibraryMapper.MapLibrary()(config.DllPath, config.ProcessName))
                    {
                        Status.InjectionOutcome = true;
                    }

                    break;
            }

            // Close the program if CloseAfterInject is checked

            if (config.CloseAfterInject)
            {
                Application.Exit();
            }

            return Status;
        }
    }
}
```

errors:
1). Error	CS1729	'LibraryMapper' does not contain a constructor that takes 0 arguments	Simple-Injector      Program.cs	10	Active
2). Error	CS0120	An object reference is required for the non-static field, method, or property 'LibraryMapper.MapLibrary()'	Simple-Injector      Program.cs	30	Active

**Comment by Dewera** [comment]
Please stop opening issues on this repository that are unrelated to the library itself.

In regards to your problems, there are several major syntactical issues that indicate you don't have an adequate understanding of C# to be using this library. Again, I will recommend you go and learn the basics of the language and once you understand that, learn how to import and use a third party library. The README of this repository give you more than enough documentation to implement the library yourself, assuming you understood the basics of C#.

**Comment by nikita-tarasov3** [comment]
@Dewera Ok. Im tried to paste.
